# Generated by Django 4.0.4 on 2022-04-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=30)),
                ('cep', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('uf', models.CharField(max_length=30)),
                ('cidade', models.CharField(choices=[('FLORIANÓPOLIS', 'Florianópolis'), ('CURITIBA', 'Curitiba'), ('SAO_PAULO', 'São Paulo'), ('RIO_DE_JANEIRO', 'Rio de Janeiro')], max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
