# Generated by Django 4.0.4 on 2022-04-12 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('animal', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('valor', models.FloatField(max_length=4)),
                ('descricao', models.CharField(max_length=255)),
                ('animal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='animal.animal')),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
                ('funcionario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.funcionario')),
            ],
        ),
    ]
