# Generated by Django 4.0.4 on 2022-04-12 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FELINO', 'Felino')], max_length=6)),
                ('peso', models.FloatField(max_length=3)),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
            ],
        ),
    ]
